# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select

driver = webdriver.Firefox()

# Test name: login
# Step # | name | target | value | comment
# 1 | open | https://www.vfsvisaservicesrussia.com/onlinevaf-finland?Country=NhRR5Ee0CQYQchCJG6L+TmyspNLVu6Jjk/QOcheOSo9pDuGGZHwtmEl7tuos+PHK&Culture=ru-RU |  | 
driver.get("https://www.vfsvisaservicesrussia.com/onlinevaf-finland?Country=NhRR5Ee0CQYQchCJG6L+TmyspNLVu6Jjk/QOcheOSo9pDuGGZHwtmEl7tuos+PHK&Culture=ru-RU")
# 2 | type | id=EmailId | kylikov_nikita@mail.ru | 
driver.find_element(By.ID, "EmailId").send_keys("kylikov_nikita@mail.ru")
# 3 | type | id=Password | V515eeC938com! | 
driver.find_element(By.ID, "Password").send_keys("V515eeC938com!")
# 4 | click | id=CaptchaInputText |  | 
driver.find_element(By.ID, "CaptchaInputText").click()

input()

# 5 | click | id=Login |  | 
driver.find_element(By.ID, "Login").click()

# Test name: kul
# Step # | name | target | value | comment
# 3 | select | id=VACLocation | label=CONSULATE GENERAL OF FINLAND, ST. PETERSBURG | 
select = Select(driver.find_element_by_name('VACLocation'))
select.select_by_visible_text("CONSULATE GENERAL OF FINLAND, ST. PETERSBURG")
# 4 | type | id=LastName | KULIKOV | 
driver.find_element(By.ID, "LastName").send_keys("KULIKOV")
# 5 | type | id=LastNameAtBirth | KULIKOV | 
driver.find_element(By.ID, "LastNameAtBirth").send_keys("KULIKOV")
# 6 | type | id=FirstName | NIKITA | 
driver.find_element(By.ID, "FirstName").send_keys("NIKITA")
# 7 | type | id=Patronymic | SERGEEVICH | 
driver.find_element(By.ID, "Patronymic").send_keys("SERGEEVICH")
# 8 | type | id=DateOfBirth | 05/02/1988 | 
driver.find_element(By.ID, "DateOfBirth").send_keys("05021988")
# 9 | type | id=PlaceOfBirth | LENINGRAD | 
driver.find_element(By.ID, "PlaceOfBirth").send_keys("LENINGRAD")
# 10 | select | id=CountryOfBirth | label=RUSSIAN FEDERATION | 
select = Select(driver.find_element_by_name('CountryOfBirth'))
select.select_by_visible_text("RUSSIAN FEDERATION")
# 11 | select | id=CurrentNationality | label=RUSSIAN FEDERATION | 
select = Select(driver.find_element_by_name('CurrentNationality'))
select.select_by_visible_text("RUSSIAN FEDERATION")
# 12 | select | id=NationalityAtBirth | label=RUSSIAN FEDERATION | 
select = Select(driver.find_element_by_name('NationalityAtBirth'))
select.select_by_visible_text("RUSSIAN FEDERATION")
# 13 | select | id=Gender | label=MALE | 
select = Select(driver.find_element_by_name('Gender'))
select.select_by_visible_text("MALE")
# 14 | select | id=MaritalStatus | label=SINGLE | 
select = Select(driver.find_element_by_name('MaritalStatus'))
select.select_by_visible_text("SINGLE")
# 15 | type | id=national | 714580417 | 
driver.find_element(By.ID, "national").send_keys("714580417")
# 16 | select | id=PassportTypeId | label=ALIEN'S PASSPORT | 
select = Select(driver.find_element_by_name('PassportTypeId'))
select.select_by_visible_text("ALIEN\'S PASSPORT")
# 17 | type | id=passport | 717580417 | 
driver.find_element(By.ID, "passport").send_keys("717580417")
# 18 | type | id=confirmpassport | 717580417 | 
driver.find_element(By.ID, "confirmpassport").send_keys("717580417")
# 19 | type | id=IssueDate | 03/02/2012 | 
driver.find_element(By.ID, "IssueDate").send_keys("03022012")
# 20 | type | id=ExpiryDate | 03/02/2022 | 
driver.find_element(By.ID, "ExpiryDate").send_keys("03022022")
# 21 | select | id=IssuedByCountry | label=RUSSIAN FEDERATION | 
select = Select(driver.find_element_by_name('IssuedByCountry'))
select.select_by_visible_text("RUSSIAN FEDERATION")
# 22 | type | id=PassportIssuedBy | FMS78036 | 
driver.find_element(By.ID, "PassportIssuedBy").send_keys("FMS78036")
# 23 | click | id=next |  | 
driver.find_element(By.ID, "next").click()
# 24 | type | id=Address | lesnoy 61/1 | 
driver.find_element(By.ID, "Address").send_keys("lesnoy 61/1")
# 25 | type | id=PostalCode | 194100 | 
driver.find_element(By.ID, "PostalCode").send_keys("194100")
# 26 | type | id=City | stpeterburg | 
driver.find_element(By.ID, "City").send_keys("stpeterburg")
# 27 | select | id=CountryId | label=RUSSIAN FEDERATION | 
select = Select(driver.find_element_by_name('CountryId'))
select.select_by_visible_text("RUSSIAN FEDERATION")
# 28 | type | id=ContactNumber | +79502203226 | 
driver.find_element(By.ID, "ContactNumber").send_keys("+79502203226")
# 29 | type | id=EmailId | kylikov_nikita@mail.ru | 
driver.find_element(By.ID, "EmailId").send_keys("kylikov_nikita@mail.ru")
# 30 | select | id=ddlCurrentOccupation | label=OTHERS | 
select = Select(driver.find_element_by_name('ddlCurrentOccupation'))
select.select_by_visible_text("OTHERS")
# 31 | type | id=OtherOccupation | MAIL | 
driver.find_element(By.ID, "OtherOccupation").send_keys("MAIL")
# 32 | type | id=txtEmployer | ExpressPost | 
driver.find_element(By.ID, "txtEmployer").send_keys("ExpressPost")
# 33 | type | id=OccupationAddress | LIGOVSKIY 50 | 
driver.find_element(By.ID, "OccupationAddress").send_keys("LIGOVSKIY 50")
# 34 | type | id=OccupationCity | stpeterburg | 
driver.find_element(By.ID, "OccupationCity").send_keys("stpeterburg")
# 35 | select | id=OccupationCountryId | label=RUSSIAN FEDERATION | 
select = Select(driver.find_element_by_name('OccupationCountryId'))
select.select_by_visible_text("RUSSIAN FEDERATION")
# 36 | type | id=OccupationContactNumber | 88126330225 | 
driver.find_element(By.ID, "OccupationContactNumber").send_keys("88126330225")
# 37 | click | id=next |  | 
driver.find_element(By.ID, "next").click()
# 38 | select | id=ddlMainTravelPurpose | label=TOURISM | 
select = Select(driver.find_element_by_name('ddlMainTravelPurpose'))
select.select_by_visible_text("TOURISM")
# 39 | select | id=ddlMainDestinationId | label=FINLAND | 
select = Select(driver.find_element_by_name('ddlMainDestinationId'))
select.select_by_visible_text("FINLAND")
# 40 | select | id=StateOfFirstEntry | label=FINLAND | 
select = Select(driver.find_element_by_name('StateOfFirstEntry'))
select.select_by_visible_text("FINLAND")
# 41 | select | id=NumberOfEntries | label=MULTI | 
select = Select(driver.find_element_by_name('NumberOfEntries'))
select.select_by_visible_text("MULTI")
# 42 | type | id=DurationOfIntendedStay | 30 | 
driver.find_element(By.ID, "DurationOfIntendedStay").send_keys("30")
# 43 | click | id=SchengenVisasIssuesDuringYes |  | 
driver.find_element(By.ID, "SchengenVisasIssuesDuringYes").click()
# 44 | type | id=FromDate1 | 01/06/2017 | 
driver.find_element(By.ID, "FromDate1").send_keys("01062017")
# 45 | type | id=ToDate1 | 31/05/2019 | 
driver.find_element(By.ID, "ToDate1").send_keys("31052019")
# 46 | click | id=FingerprintsCollectedYes |  | 
driver.find_element(By.ID, "FingerprintsCollectedYes").click()
# 47 | type | id=IntentedDateOfArrival | 01/06/2020 | 
driver.find_element(By.ID, "IntentedDateOfArrival").send_keys("01062020")
# 48 | type | id=IntentedDateOfDeparture | 15/06/2020 | 
driver.find_element(By.ID, "IntentedDateOfDeparture").send_keys("15062020")
# 49 | click | id=next |  | 
driver.find_element(By.ID, "next").click()
# 50 | select | id=ddlinvitingid | label=NO INVITATION | 
select = Select(driver.find_element_by_name('ddlinvitingid'))
select.select_by_visible_text("NO INVITATION")
# 51 | click | id=1 |  | 
driver.find_element(By.ID, "1").click()
# 52 | click | id=CASH |  | 
driver.find_element(By.ID, "CASH").click()
# 53 | click | id=rdominortru |  | 
driver.find_element(By.ID, "rdominortru").click()
# 54 | click | id=next |  | 
driver.find_element(By.ID, "next").click()
# 55 | click | name=SAVE |  | 
driver.find_element(By.NAME, "SAVE").click()
# 56 | mouseOver | id=rdbYes |  | 
# element = driver.find_element(By.ID, "rdbYes")
# actions = ActionChains(driver)
# actions.move_to_element(element).perform()
# 57 | click | id=rdbYes |  | 
driver.find_element(By.ID, "rdbYes").click()
# 58 | mouseOut | id=rdbYes |  | 
# element = driver.find_element(By.CSS_SELECTOR, "body")
# actions = ActionChains(driver)
# actions.move_to_element(element, 0, 0).perform()
# 59 | click | id=rdbTourist |  | 
driver.find_element(By.ID, "rdbTourist").click()
# 60 | click | id=btnSubmit |  | 
driver.find_element(By.ID, "btnSubmit").click()