# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
driver = webdriver.Firefox()
# class TestTest():
#   def setup_method(self, method):
#     driver = webdriver.Firefox()
#     vars = {}
  
#   def teardown_method(self, method):
#     driver.quit()
  
#   def test_test(self):
# Test name: test
# Step # | name | target | value | comment
# 1 | open | /OnlineVAF-Finland/Applicant/Page1 |  | 
driver.get(r"https://www.vfsvisaservicesrussia.com/onlinevaf-finland?Country=NhRR5Ee0CQYQchCJG6L+TmyspNLVu6Jjk/QOcheOSo9pDuGGZHwtmEl7tuos+PHK&Culture=ru-RU")

# try:
    # driver.get("https://www.vfsvisaservicesrussia.com/OnlineVAF-Finland/Applicant/Page1")
    # select = Select(driver.find_element_by_name('VACLocation'))
# except:
driver.find_element(By.ID, "EmailId").send_keys("kylikov_nikita@mail.ru")
driver.find_element(By.ID, "Password").send_keys("V515eeC938com!")
driver.find_element(By.ID, "CaptchaInputText").click()
input()
driver.find_element(By.ID, "Login").click()
time.sleep(2)

# 3 | select | id=VACLocation | label=CONSULATE GENERAL OF FINLAND, ST. PETERSBURG | 
dropdown = driver.find_element(By.ID, "VACLocation")
dropdown.find_element(By.XPATH, "//option[. = 'CONSULATE GENERAL OF FINLAND, ST. PETERSBURG']").click()
# 4 | type | id=LastName | kulikov | 
driver.find_element(By.ID, "LastName").send_keys("kulikov")
# 5 | type | id=LastNameAtBirth | kulikov | 
driver.find_element(By.ID, "LastNameAtBirth").send_keys("kulikov")
# 6 | type | id=FirstName | nikita | 
driver.find_element(By.ID, "FirstName").send_keys("nikita")
# 7 | type | id=Patronymic | sergeevich | 
driver.find_element(By.ID, "Patronymic").send_keys("sergeevich")
# 8 | type | id=DateOfBirth | 05/02/1988 | 
driver.find_element(By.ID, "DateOfBirth").send_keys("05021988")
# 9 | type | id=PlaceOfBirth | leningrad | 
driver.find_element(By.ID, "PlaceOfBirth").send_keys("leningrad")
# 10 | select | id=CountryOfBirth | label=SOVIET UNION | 
dropdown = driver.find_element(By.ID, "CountryOfBirth")
dropdown.find_element(By.XPATH, "//option[. = 'SOVIET UNION']").click()
# 11 | select | id=CurrentNationality | label=RUSSIAN FEDERATION | 
dropdown = driver.find_element(By.ID, "CurrentNationality")
dropdown.find_element(By.XPATH, "//option[. = 'RUSSIAN FEDERATION']").click()
# 12 | select | id=NationalityAtBirth | label=SOVIET UNION | 
dropdown = driver.find_element(By.ID, "NationalityAtBirth")
dropdown.find_element(By.XPATH, "//option[. = 'SOVIET UNION']").click()
# 13 | select | id=Gender | label=MALE | 
dropdown = driver.find_element(By.ID, "Gender")
dropdown.find_element(By.XPATH, "//option[. = 'MALE']").click()
# 14 | select | id=MaritalStatus | label=SINGLE | 
dropdown = driver.find_element(By.ID, "MaritalStatus")
dropdown.find_element(By.XPATH, "//option[. = 'SINGLE']").click()
# 15 | select | id=PassportTypeId | label=ALIEN'S PASSPORT | 
dropdown = driver.find_element(By.ID, "PassportTypeId")
dropdown.find_element(By.XPATH, "//option[. = 'ALIEN\'S PASSPORT']").click()
# 16 | type | id=passport | 717580417 | 
driver.find_element(By.ID, "passport").send_keys("717580417")
# 17 | type | id=confirmpassport | 717580417 | 
driver.find_element(By.ID, "confirmpassport").send_keys("717580417")
# 18 | type | id=IssueDate | 03/02/2012 | 
driver.find_element(By.ID, "IssueDate").send_keys("03022012")
# 19 | type | id=ExpiryDate | 03/02/2022 | 
driver.find_element(By.ID, "ExpiryDate").send_keys("03022022")
# 20 | select | id=IssuedByCountry | label=RUSSIAN FEDERATION | 
dropdown = driver.find_element(By.ID, "IssuedByCountry")
dropdown.find_element(By.XPATH, "//option[. = 'RUSSIAN FEDERATION']").click()
# 21 | type | id=PassportIssuedBy | FMS78036 | 
driver.find_element(By.ID, "PassportIssuedBy").send_keys("FMS78036")

