# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test111():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_111(self):
self.driver.get("https://www.vfsvisaservicesrussia.com/OnlineVAF-Finland/Applicant/Page1")
self.driver.set_window_size(1233, 968)
self.driver.execute_script("window.scrollTo(0,241)")
self.driver.find_element(By.ID, "CountryOfBirth").click()
dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
dropdown.find_element(By.XPATH, "//option[. = 'SOVIET UNION']").click()
self.driver.find_element(By.CSS_SELECTOR, "#CountryOfBirth > option:nth-child(261)").click()
self.driver.execute_script("window.scrollTo(0,408)")
self.driver.find_element(By.ID, "CountryOfBirth").click()
self.driver.find_element(By.ID, "CurrentNationality").click()
dropdown = self.driver.find_element(By.ID, "CurrentNationality")
dropdown.find_element(By.XPATH, "//option[. = 'RUSSIAN FEDERATION']").click()
self.driver.find_element(By.ID, "CurrentNationality").click()
driver.find_element(By.CSS_SELECTOR, "#CurrentNationality > option:nth-child(229)").click()
  
