# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


driver = webdriver.Firefox()

# Test name: login
# Step # | name | target | value | comment
# 1 | open | https://www.vfsvisaservicesrussia.com/onlinevaf-finland?Country=NhRR5Ee0CQYQchCJG6L+TmyspNLVu6Jjk/QOcheOSo9pDuGGZHwtmEl7tuos+PHK&Culture=ru-RU |  | 
driver.get("https://www.vfsvisaservicesrussia.com/onlinevaf-finland?Country=NhRR5Ee0CQYQchCJG6L+TmyspNLVu6Jjk/QOcheOSo9pDuGGZHwtmEl7tuos+PHK&Culture=ru-RU")
# 2 | type | id=EmailId | kylikov_nikita@mail.ru | 
driver.find_element(By.ID, "EmailId").send_keys("kylikov_nikita@mail.ru")
# 3 | type | id=Password | V515eeC938com! | 
driver.find_element(By.ID, "Password").send_keys("V515eeC938com!")
# 4 | click | id=CaptchaInputText |  | 
driver.find_element(By.ID, "CaptchaInputText").click()
  
