# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestKul():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_kul(self):
    # Test name: kul
    # Step # | name | target | value | comment
    # 1 | open | https://www.vfsvisaservicesrussia.com/OnlineVAF-Finland/Applicant/Page1 |  | 
    self.driver.get("https://www.vfsvisaservicesrussia.com/OnlineVAF-Finland/Applicant/Page1")
    # 2 | setWindowSize | 923x831 |  | 
    self.driver.set_window_size(923, 831)
    # 3 | runScript | window.scrollTo(0,306) |  | 
    self.driver.execute_script("window.scrollTo(0,306)")
    # 4 | click | id=VACLocation |  | 
    self.driver.find_element(By.ID, "VACLocation").click()
    # 5 | select | id=VACLocation | label=CONSULATE GENERAL OF FINLAND, ST. PETERSBURG | 
    dropdown = self.driver.find_element(By.ID, "VACLocation")
    dropdown.find_element(By.XPATH, "//option[. = 'CONSULATE GENERAL OF FINLAND, ST. PETERSBURG']").click()
    # 6 | click | css=#VACLocation > option:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#VACLocation > option:nth-child(2)").click()
    # 7 | runScript | window.scrollTo(0,306) |  | 
    self.driver.execute_script("window.scrollTo(0,306)")
    # 8 | click | id=LastName |  | 
    self.driver.find_element(By.ID, "LastName").click()
    # 9 | type | id=LastName | kulikov | 
    self.driver.find_element(By.ID, "LastName").send_keys("kulikov")
    # 10 | type | id=FirstName | nikita | 
    self.driver.find_element(By.ID, "FirstName").send_keys("nikita")
    # 11 | type | id=Patronymic | sergeevich | 
    self.driver.find_element(By.ID, "Patronymic").send_keys("sergeevich")
    # 12 | runScript | window.scrollTo(0,473) |  | 
    self.driver.execute_script("window.scrollTo(0,473)")
    # 13 | type | id=DateOfBirth | 05/02/1988 | 
    self.driver.find_element(By.ID, "DateOfBirth").send_keys("05/02/1988")
    # 14 | click | id=PlaceOfBirth |  | 
    self.driver.find_element(By.ID, "PlaceOfBirth").click()
    # 15 | type | id=PlaceOfBirth | leningrad | 
    self.driver.find_element(By.ID, "PlaceOfBirth").send_keys("leningrad")
    # 16 | select | id=CountryOfBirth | label=REFUGEE (1951 CONVENTION) | 
    dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'REFUGEE (1951 CONVENTION)']").click()
    # 17 | select | id=CountryOfBirth | label=REFUGEE (OTHER) | 
    dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'REFUGEE (OTHER)']").click()
    # 18 | select | id=CountryOfBirth | label=REUNION | 
    dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'REUNION']").click()
    # 19 | select | id=CountryOfBirth | label=RHODESIA | 
    dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'RHODESIA']").click()
    # 20 | select | id=CountryOfBirth | label=ROMANIA | 
    dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'ROMANIA']").click()
    # 21 | select | id=CountryOfBirth | label=RUSSIAN FEDERATION | 
    dropdown = self.driver.find_element(By.ID, "CountryOfBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'RUSSIAN FEDERATION']").click()
    # 22 | select | id=CurrentNationality | label=REFUGEE (1951 CONVENTION) | 
    dropdown = self.driver.find_element(By.ID, "CurrentNationality")
    dropdown.find_element(By.XPATH, "//option[. = 'REFUGEE (1951 CONVENTION)']").click()
    # 23 | select | id=CurrentNationality | label=RUSSIAN FEDERATION | 
    dropdown = self.driver.find_element(By.ID, "CurrentNationality")
    dropdown.find_element(By.XPATH, "//option[. = 'RUSSIAN FEDERATION']").click()
    # 24 | runScript | window.scrollTo(0,708) |  | 
    self.driver.execute_script("window.scrollTo(0,708)")
    # 25 | select | id=NationalityAtBirth | label=REFUGEE (1951 CONVENTION) | 
    dropdown = self.driver.find_element(By.ID, "NationalityAtBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'REFUGEE (1951 CONVENTION)']").click()
    # 26 | select | id=NationalityAtBirth | label=RUSSIAN FEDERATION | 
    dropdown = self.driver.find_element(By.ID, "NationalityAtBirth")
    dropdown.find_element(By.XPATH, "//option[. = 'RUSSIAN FEDERATION']").click()
    # 27 | select | id=Gender | label=MALE | 
    dropdown = self.driver.find_element(By.ID, "Gender")
    dropdown.find_element(By.XPATH, "//option[. = 'MALE']").click()
    # 28 | click | id=MaritalStatus |  | 
    self.driver.find_element(By.ID, "MaritalStatus").click()
    # 29 | select | id=MaritalStatus | label=SINGLE | 
    dropdown = self.driver.find_element(By.ID, "MaritalStatus")
    dropdown.find_element(By.XPATH, "//option[. = 'SINGLE']").click()
    # 30 | click | css=#MaritalStatus > option:nth-child(6) |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#MaritalStatus > option:nth-child(6)").click()
    # 31 | runScript | window.scrollTo(0,714) |  | 
    self.driver.execute_script("window.scrollTo(0,714)")
    # 32 | click | css=body |  | 
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    # 33 | mouseOver | id=rdominortru |  | 
    element = self.driver.find_element(By.ID, "rdominortru")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 34 | mouseOut | id=rdominortru |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 35 | mouseOver | id=rdominortru |  | 
    element = self.driver.find_element(By.ID, "rdominortru")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 36 | mouseOut | id=rdominortru |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 37 | mouseOver | id=rdominortru |  | 
    element = self.driver.find_element(By.ID, "rdominortru")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    # 38 | mouseOut | id=rdominortru |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(driver)
    actions.move_to_element(element, 0, 0).perform()
    # 39 | runScript | window.scrollTo(0,1000) |  | 
    self.driver.execute_script("window.scrollTo(0,1000)")
    # 40 | runScript | window.scrollTo(0,1218) |  | 
    self.driver.execute_script("window.scrollTo(0,1218)")
  
